openapi: '3.0.3'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:3000
paths:
  /hello-world:
    get:
      responses:
        '200':
          description: OK

  /login:
    post:
      summary: Faz login com email e senha
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: usuario@email.com
                password:
                  type: string
                  format: password
                  example: senha123
      responses:
        '200':
          description: Login bem-sucedido
